### ISSUE TITLE
Corruption when packets are too large

### ISSUE THREAD

**Issue by Gargaj** [JordiRos/remoteimgui#14]
Websocket packet size is 64k, but sometimes LZ4 can't compress the packet down enough (typical situation would be large noisy graphs) and just sends a packet with `csize == 0` - the browser renderer then gets a corrupted packet and the visuals glitch out.

The solution would be to break packets down to smaller ones, send them, and make JS collect and concatenate them until the final packet arrives, at which point it should process them.

**Comment by Gargaj** [comment]
Actually https://github.com/JordiRos/remoteimgui/blob/master/src/app/imgui_remote.h#L386 suggests it's sending not 64k but 256k packets...

**Comment by Gargaj** [comment]
I've been testing a fix to this; what it does is uses the magic number field to indicate if it's a partial or a "terminator" packet; if it's a partial packet, it just unpacks it on the JS side and holds the unpacked data without processing, for final packets it concatenates all the data held and processes it.

This works for the most part, but there's still some weirdness with it where every few frames the image glitches out. because the unpacked data was incorrect...?

I'll see if I can get a PR up.

**Comment by Gargaj** [comment]
Here's what I have so far, if you wanna take a look: https://github.com/Gargaj/remoteimgui/commit/ec8cc17a8c0a90a4b1ace4c61e14e9c87d70916d

**Comment by JordiRos** [comment]
I like this solution, it looks like it should work. Perhaps the glitch is now caused by a different issue.
Definitely worth merging, thanks!

**Comment by Gargaj** [comment]
I was looking some more into it; the problem is definitely with 16bit indexbuffers + WebGL not supporting vertex indices.
